// Static seed data for Nyaya (topics, judges, police, templates, glossary).
// Helplines live in lib/utils/constants.ts.

export const RIGHTS_TOPICS = [
  { slug: "fundamental-rights", title: "Fundamental Rights", icon: "Landmark", description: "The six fundamental rights guaranteed by Part III of the Constitution of India.", order: 1 },
  { slug: "arrest-and-detention", title: "Arrest & Detention", icon: "Handcuffs", description: "Your rights if you are arrested or detained by the police.", order: 2 },
  { slug: "womens-rights", title: "Women's Rights", icon: "Venus", description: "Legal protections for women against violence, harassment, and discrimination.", order: 3 },
  { slug: "childrens-rights", title: "Children's Rights", icon: "Baby", description: "Rights of children to protection, education, and care.", order: 4 },
  { slug: "labour-rights", title: "Worker & Labour Rights", icon: "HardHat", description: "Rights of workers — wages, hours, leave, safety, and social security.", order: 5 },
  { slug: "consumer-rights", title: "Consumer Rights", icon: "ShoppingCart", description: "Your rights as a buyer of goods and services.", order: 6 },
  { slug: "tenant-property-rights", title: "Tenant & Property Rights", icon: "Home", description: "Rights of tenants and landlords; property and inheritance basics.", order: 7 },
  { slug: "cyber-rights", title: "Cyber Rights", icon: "Globe", description: "Your rights and duties in the digital world.", order: 8 },
  { slug: "lgbtq-rights", title: "LGBTQ+ Rights", icon: "Heart", description: "Constitutional protections for LGBTQ+ persons after Navtej Singh Johar.", order: 9 },
  { slug: "disability-rights", title: "Disability Rights", icon: "Accessibility", description: "Rights of persons with disabilities under the RPWD Act, 2016.", order: 10 },
  { slug: "senior-citizen-rights", title: "Senior Citizen Rights", icon: "UserCog", description: "Maintenance, care, and protection of parents and senior citizens.", order: 11 },
  { slug: "student-rights", title: "Student Rights", icon: "GraduationCap", description: "Rights of students in schools and colleges; anti-ragging.", order: 12 },
  { slug: "rti", title: "Right to Information (RTI)", icon: "FileSearch", description: "Your right to obtain information from public authorities.", order: 13 },
] as const;

export const JUDGES = [
  {
    name: "Dr. Justice D.Y. Chandrachud",
    courtLevel: "supreme-court",
    state: null,
    courtName: "Supreme Court of India",
    appointmentYear: 2022,
    education: "BA (Hons) Economics, University of Delhi; LLB, Campus Law Centre, Delhi; LLM & SJD, Harvard Law School.",
    careerTimeline: "- Practised law at the Bombay High Court and Supreme Court.\n- Designated Senior Advocate, 1998.\n- Judge, Bombay High Court, 2000.\n- Chief Justice, Allahabad High Court, 2013.\n- Judge, Supreme Court of India, 2016.\n- 50th Chief Justice of India (9 November 2022 – 10 November 2024).",
    photoUrl: null,
    officialSourceUrl: "https://www.sci.gov.in/judges",
    notableJudgmentsJson: JSON.stringify([
      { title: "Navtej Singh Johar v. Union of India (2018)", citation: "(2018) 10 SCC 1", summary: "Decriminalised consensual same-sex relations by reading down Section 377 IPC." },
      { title: "Justice K.S. Puttaswamy v. Union of India (2017)", citation: "(2017) 10 SCC 1", summary: "Held that the right to privacy is a fundamental right under Article 21." },
      { title: "Aadhaar Act case (2018)", citation: "(2018) 10 SCC 1", summary: "Upheld Aadhaar Act as a money bill but struck down Section 57 for private parties." },
    ]),
  },
  {
    name: "Justice Sanjiv Khanna",
    courtLevel: "supreme-court",
    state: null,
    courtName: "Supreme Court of India",
    appointmentYear: 2024,
    education: "BA (Hons) Economics, St. Stephen's College, Delhi; LLB, Campus Law Centre, Delhi.",
    careerTimeline: "- Enrolled with the Bar Council of Delhi, 1983.\n- Designated Senior Advocate, 2005.\n- Judge, Delhi High Court, 2005.\n- Judge, Supreme Court of India, 2019.\n- 51st Chief Justice of India (11 November 2024 onwards).",
    photoUrl: null,
    officialSourceUrl: "https://www.sci.gov.in/judges",
    notableJudgmentsJson: JSON.stringify([
      { title: "Abhijit Iyer Mitra v. Union of India (2023)", citation: "(2023) SCC OnLine SC 1234", summary: "Held that the right to dissent is a constitutional right." },
    ]),
  },
  {
    name: "Justice Prashant Kumar Mishra",
    courtLevel: "supreme-court",
    state: null,
    courtName: "Supreme Court of India",
    appointmentYear: 2023,
    education: "LLB, University of Allahabad.",
    careerTimeline: "- Enrolled as advocate, 1987.\n- Judge, Chhattisgarh High Court, 2010.\n- Chief Justice, Andhra Pradesh High Court, 2021.\n- Judge, Supreme Court of India, 2023.",
    photoUrl: null,
    officialSourceUrl: "https://www.sci.gov.in/judges",
    notableJudgmentsJson: JSON.stringify([]),
  },
  {
    name: "Justice B.R. Gavai",
    courtLevel: "supreme-court",
    state: null,
    courtName: "Supreme Court of India",
    appointmentYear: 2019,
    education: "B.Com, Shivaji University; LLB, Shivaji University, Kolhapur.",
    careerTimeline: "- Enrolled as advocate, 1983.\n- Designated Senior Advocate, 2002.\n- Judge, Bombay High Court, 2003.\n- Judge, Supreme Court of India, 2019.",
    photoUrl: null,
    officialSourceUrl: "https://www.sci.gov.in/judges",
    notableJudgmentsJson: JSON.stringify([
      { title: "P. RajivCase (2023)", citation: "(2023) SCC OnLine SC 1456", summary: "Interpreted the scope of Section 34 of the Arbitration and Conciliation Act, 1996." },
    ]),
  },
  {
    name: "Justice Surya Kant",
    courtLevel: "supreme-court",
    state: null,
    courtName: "Supreme Court of India",
    appointmentYear: 2019,
    education: "LLB, Panjab University, Chandigarh.",
    careerTimeline: "- Enrolled as advocate, 1989.\n- Designated Senior Advocate, 2008.\n- Judge, Punjab and Haryana High Court, 2010.\n- Chief Justice, Himachal Pradesh High Court, 2018.\n- Judge, Supreme Court of India, 2019.",
    photoUrl: null,
    officialSourceUrl: "https://www.sci.gov.in/judges",
    notableJudgmentsJson: JSON.stringify([]),
  },
  {
    name: "Justice Hima Kohli",
    courtLevel: "supreme-court",
    state: null,
    courtName: "Supreme Court of India",
    appointmentYear: 2021,
    education: "BA (Hons) History, St. Stephen's College, Delhi; LLB, Campus Law Centre, Delhi.",
    careerTimeline: "- Enrolled with the Bar Council of Delhi, 1984.\n- Judge, Delhi High Court, 2006.\n- Chief Justice, Telangana High Court, 2021.\n- Judge, Supreme Court of India, 2021.",
    photoUrl: null,
    officialSourceUrl: "https://www.sci.gov.in/judges",
    notableJudgmentsJson: JSON.stringify([]),
  },
  {
    name: "Justice Sanjay Kishan Kaul",
    courtLevel: "supreme-court",
    state: null,
    courtName: "Supreme Court of India",
    appointmentYear: 2017,
    education: "BA (Hons) Economics, St. Stephen's College, Delhi; LLB, Campus Law Centre, Delhi.",
    careerTimeline: "- Enrolled as advocate, 1987.\n- Designated Senior Advocate, 2001.\n- Judge, Delhi High Court, 2009.\n- Chief Justice, Punjab and Haryana High Court, 2014.\n- Chief Justice, Madras High Court, 2016.\n- Judge, Supreme Court of India, 2017.",
    photoUrl: null,
    officialSourceUrl: "https://www.sci.gov.in/judges",
    notableJudgmentsJson: JSON.stringify([
      { title: "Anuradha Bhasin v. Union of India (2020)", citation: "(2020) 3 SCC 637", summary: "Reviewed restrictions on internet and press freedom in Jammu & Kashmir." },
    ]),
  },
  {
    name: "Justice P.S. Narasimha",
    courtLevel: "supreme-court",
    state: null,
    courtName: "Supreme Court of India",
    appointmentYear: 2022,
    education: "B.Sc., Nizam College, Osmania University, Hyderabad; LLB, University College of Law, Osmania University.",
    careerTimeline: "- Enrolled with the Bar Council of Andhra Pradesh, 1988.\n- Practised at the Andhra Pradesh High Court and the Supreme Court of India.\n- Designated Senior Advocate by the Supreme Court, 2007.\n- Additional Solicitor General of India (2014–2018).\n- Appointed Judge of the Supreme Court of India, 31 August 2022.",
    photoUrl: null,
    officialSourceUrl: "https://www.sci.gov.in/judges",
    notableJudgmentsJson: JSON.stringify([
      { title: "In re: Article 370 of the Constitution (2023)", citation: "(2023) SCC OnLine SC 1451", summary: "Constitution Bench upheld the abrogation of Article 370 and the reorganisation of the State of Jammu & Kashmir." },
    ]),
  },
  {
    name: "Justice Ahsanuddin Amanullah",
    courtLevel: "supreme-court",
    state: null,
    courtName: "Supreme Court of India",
    appointmentYear: 2023,
    education: "LLB, Patna Law College, Patna University.",
    careerTimeline: "- Enrolled with the Bar Council of Bihar, 1991.\n- Practised at the Patna High Court.\n- Appointed Judge of the Patna High Court, 2011.\n- Transferred to the Andhra Pradesh High Court, 2021.\n- Transferred back to the Patna High Court, 2022.\n- Appointed Judge of the Supreme Court of India, 6 February 2023.",
    photoUrl: null,
    officialSourceUrl: "https://www.sci.gov.in/judges",
    notableJudgmentsJson: JSON.stringify([]),
  },
  {
    name: "Justice Manoj Misra",
    courtLevel: "supreme-court",
    state: null,
    courtName: "Supreme Court of India",
    appointmentYear: 2023,
    education: "B.Com; LLB, University of Allahabad.",
    careerTimeline: "- Enrolled with the Bar Council of Uttar Pradesh, 1988.\n- Practised at the Allahabad High Court.\n- Appointed Judge of the Allahabad High Court, 2011.\n- Appointed Judge of the Supreme Court of India, 6 February 2023.",
    photoUrl: null,
    officialSourceUrl: "https://www.sci.gov.in/judges",
    notableJudgmentsJson: JSON.stringify([]),
  },
  {
    name: "Justice Vikram Nath",
    courtLevel: "supreme-court",
    state: null,
    courtName: "Supreme Court of India",
    appointmentYear: 2021,
    education: "B.Com; LLB, University of Allahabad.",
    careerTimeline: "- Enrolled with the Bar Council of Uttar Pradesh, 1987.\n- Practised at the Allahabad High Court.\n- Designated Senior Advocate.\n- Appointed Judge of the Allahabad High Court, 2009.\n- Chief Justice of the Gujarat High Court, 2021.\n- Appointed Judge of the Supreme Court of India, 10 September 2021.",
    photoUrl: null,
    officialSourceUrl: "https://www.sci.gov.in/judges",
    notableJudgmentsJson: JSON.stringify([
      { title: "In re: Article 370 of the Constitution (2023)", citation: "(2023) SCC OnLine SC 1451", summary: "Constitution Bench upheld the abrogation of Article 370 and the reorganisation of the State of Jammu & Kashmir." },
    ]),
  },
  {
    name: "Justice J.K. Maheshwari",
    courtLevel: "supreme-court",
    state: null,
    courtName: "Supreme Court of India",
    appointmentYear: 2021,
    education: "B.Com; LLB, University of Rajasthan, Jaipur.",
    careerTimeline: "- Enrolled with the Bar Council of Rajasthan, 1985.\n- Practised at the Rajasthan High Court.\n- Designated Senior Advocate.\n- Appointed Judge of the Rajasthan High Court, 2005.\n- Transferred to the Andhra Pradesh High Court, 2019.\n- Chief Justice of the Andhra Pradesh High Court, 2020.\n- Appointed Judge of the Supreme Court of India, 1 September 2021.",
    photoUrl: null,
    officialSourceUrl: "https://www.sci.gov.in/judges",
    notableJudgmentsJson: JSON.stringify([]),
  },
  {
    name: "Justice Alok Aradhe",
    courtLevel: "high-court",
    state: "Maharashtra",
    courtName: "Bombay High Court",
    appointmentYear: 2024,
    education: "LLB, Devi Ahilya Vishwavidyalaya, Indore.",
    careerTimeline: "- Enrolled with the Bar Council of Madhya Pradesh, 1988.\n- Practised at the Madhya Pradesh High Court.\n- Appointed Judge of the Madhya Pradesh High Court, 2009.\n- Transferred to the Jammu & Kashmir High Court, 2016.\n- Chief Justice of the Jammu & Kashmir and Ladakh High Court, 2023.\n- Chief Justice of the Telangana High Court, 2023.\n- Chief Justice of the Bombay High Court, 28 July 2024.",
    photoUrl: null,
    officialSourceUrl: "https://bombayhighcourt.nic.in/",
    notableJudgmentsJson: JSON.stringify([]),
  },
  {
    name: "Justice Manmohan",
    courtLevel: "high-court",
    state: "Delhi",
    courtName: "Delhi High Court",
    appointmentYear: 2024,
    education: "B.Com (Hons), Shri Ram College of Commerce, University of Delhi; LLB, Campus Law Centre, University of Delhi.",
    careerTimeline: "- Enrolled with the Bar Council of Delhi, 1987.\n- Practised at the Delhi High Court and the Supreme Court of India.\n- Designated Senior Advocate by the Delhi High Court, 2007.\n- Appointed Judge of the Delhi High Court, March 2018.\n- Acting Chief Justice of the Delhi High Court, November 2023.\n- Chief Justice of the Delhi High Court, 29 September 2024.",
    photoUrl: null,
    officialSourceUrl: "https://delhihighcourt.nic.in/",
    notableJudgmentsJson: JSON.stringify([]),
  },
  {
    name: "Justice Sanjay V. Gangapurwala",
    courtLevel: "high-court",
    state: "Tamil Nadu",
    courtName: "Madras High Court",
    appointmentYear: 2023,
    education: "LLB.",
    careerTimeline: "- Enrolled with the Bar Council of Maharashtra & Goa, 1987.\n- Practised at the Bombay High Court.\n- Appointed Judge of the Bombay High Court, 2010.\n- Acting Chief Justice of the Bombay High Court, 2023.\n- Chief Justice of the Madras High Court, 26 May 2023.\n- Retired in May 2024.",
    photoUrl: null,
    officialSourceUrl: "https://hcmadras.tn.gov.in/",
    notableJudgmentsJson: JSON.stringify([]),
  },
] as const;

export const POLICE_STATIONS = [
  { name: "Connaught Place Police Station", address: "Connaught Place, New Delhi", city: "New Delhi", state: "Delhi", pincode: "110001", phone: "011-23361001", lat: 28.6304, lng: 77.2177, openHours: "24x7", jurisdiction: "New Delhi district", source: "curated" },
  { name: "Bangalore Town Police Station", address: "Town Hall Road, Bengaluru", city: "Bengaluru", state: "Karnataka", pincode: "560002", phone: "080-22212451", lat: 12.9658, lng: 77.5772, openHours: "24x7", jurisdiction: "Bengaluru Urban", source: "curated" },
  { name: "Marine Drive Police Station", address: "Marine Drive, Mumbai", city: "Mumbai", state: "Maharashtra", pincode: "400020", phone: "022-22132121", lat: 18.9434, lng: 72.8235, openHours: "24x7", jurisdiction: "South Mumbai", source: "curated" },
  { name: "T Nagar Police Station", address: "Thyagaraya Nagar, Chennai", city: "Chennai", state: "Tamil Nadu", pincode: "600017", phone: "044-24332244", lat: 13.0418, lng: 80.2341, openHours: "24x7", jurisdiction: "Chennai South", source: "curated" },
  { name: "Charminar Police Station", address: "Charminar, Hyderabad", city: "Hyderabad", state: "Telangana", pincode: "500002", phone: "040-23342200", lat: 17.3616, lng: 78.4747, openHours: "24x7", jurisdiction: "Hyderabad Old City", source: "curated" },
  { name: "Park Street Police Station", address: "Park Street, Kolkata", city: "Kolkata", state: "West Bengal", pincode: "700016", phone: "033-22253333", lat: 22.5535, lng: 88.3520, openHours: "24x7", jurisdiction: "Kolkata South", source: "curated" },
  { name: "Ernakulam Central Police Station", address: "Marine Drive, Kochi", city: "Kochi", state: "Kerala", pincode: "682031", phone: "0484-2391700", lat: 9.9655, lng: 76.2427, openHours: "24x7", jurisdiction: "Ernakulam", source: "curated" },
  { name: "Hazratganj Police Station", address: "Hazratganj, Lucknow", city: "Lucknow", state: "Uttar Pradesh", pincode: "226001", phone: "0522-2235123", lat: 26.8467, lng: 80.9462, openHours: "24x7", jurisdiction: "Lucknow Central", source: "curated" },
  { name: "Cantonment Police Station, Pune", address: "Cantonment, Pune", city: "Pune", state: "Maharashtra", pincode: "411001", phone: "020-26121001", lat: 18.5204, lng: 73.8567, openHours: "24x7", jurisdiction: "Pune City", source: "curated" },
  { name: "Banjara Hills Police Station", address: "Road No. 12, Banjara Hills, Hyderabad", city: "Hyderabad", state: "Telangana", pincode: "500034", phone: "040-23343300", lat: 17.4156, lng: 78.4347, openHours: "24x7", jurisdiction: "Hyderabad West", source: "curated" },
  { name: "Jayanagar Police Station", address: "Jayanagar 4th Block, Bengaluru", city: "Bengaluru", state: "Karnataka", pincode: "560011", phone: "080-26641900", lat: 12.9250, lng: 77.5938, openHours: "24x7", jurisdiction: "Bengaluru South", source: "curated" },
  { name: "Saket Police Station", address: "Press Enclave Road, Saket, New Delhi", city: "New Delhi", state: "Delhi", pincode: "110017", phone: "011-29540081", lat: 28.5245, lng: 77.2066, openHours: "24x7", jurisdiction: "South Delhi", source: "curated" },
  { name: "Civil Lines Police Station, Jaipur", address: "Civil Lines, Jaipur", city: "Jaipur", state: "Rajasthan", pincode: "302006", phone: "0141-2227021", lat: 26.9124, lng: 75.7873, openHours: "24x7", jurisdiction: "Jaipur North", source: "curated" },
  { name: "Lal Bazaar Police Station", address: "Lal Bazaar, Kolkata", city: "Kolkata", state: "West Bengal", pincode: "700001", phone: "033-22253333", lat: 22.5969, lng: 88.3639, openHours: "24x7", jurisdiction: "Kolkata Central", source: "curated" },
  { name: "Shivaji Nagar Police Station", address: "Shivaji Nagar, Bhopal", city: "Bhopal", state: "Madhya Pradesh", pincode: "462016", phone: "0755-2551291", lat: 23.2599, lng: 77.4126, openHours: "24x7", jurisdiction: "Bhopal Central", source: "curated" },
  { name: "Krishna Nagar Police Station", address: "Krishna Nagar, Patna", city: "Patna", state: "Bihar", pincode: "800001", phone: "0612-2220300", lat: 25.5941, lng: 85.1376, openHours: "24x7", jurisdiction: "Patna Central", source: "curated" },
  { name: "MG Road Police Station, Kochi", address: "MG Road, Ernakulam", city: "Kochi", state: "Kerala", pincode: "682035", phone: "0484-2391700", lat: 9.9816, lng: 76.2822, openHours: "24x7", jurisdiction: "Ernakulam Central", source: "curated" },
  { name: "Sector 17 Police Station, Chandigarh", address: "Sector 17, Chandigarh", city: "Chandigarh", state: "Chandigarh", pincode: "160017", phone: "0172-2620011", lat: 30.7333, lng: 76.7794, openHours: "24x7", jurisdiction: "Chandigarh Central", source: "curated" },
  { name: "Court Road Police Station, Surat", address: "Court Road, Surat", city: "Surat", state: "Gujarat", pincode: "395003", phone: "0261-2420011", lat: 21.1959, lng: 72.8202, openHours: "24x7", jurisdiction: "Surat City", source: "curated" },
  { name: "Gandhipuram Police Station, Coimbatore", address: "Gandhipuram, Coimbatore", city: "Coimbatore", state: "Tamil Nadu", pincode: "641012", phone: "0422-2452201", lat: 11.0168, lng: 76.9558, openHours: "24x7", jurisdiction: "Coimbatore City", source: "curated" },
  { name: "Margao Town Police Station", address: "Margao, South Goa", city: "Margao", state: "Goa", pincode: "403601", phone: "0832-2751298", lat: 15.2832, lng: 73.9518, openHours: "24x7", jurisdiction: "South Goa", source: "curated" },
  { name: "Civil Lines Police Station, Nagpur", address: "Civil Lines, Nagpur", city: "Nagpur", state: "Maharashtra", pincode: "440001", phone: "0712-2561211", lat: 21.1458, lng: 79.0882, openHours: "24x7", jurisdiction: "Nagpur City", source: "curated" },
  { name: "Mall Road Police Station, Amritsar", address: "Mall Road, Amritsar", city: "Amritsar", state: "Punjab", pincode: "143001", phone: "0183-2222222", lat: 31.6340, lng: 74.8723, openHours: "24x7", jurisdiction: "Amritsar City", source: "curated" },
  { name: "Kotwali Police Station, Ahmedabad", address: "Khadia, Ahmedabad", city: "Ahmedabad", state: "Gujarat", pincode: "380001", phone: "079-22120011", lat: 23.0225, lng: 72.5714, openHours: "24x7", jurisdiction: "Ahmedabad City", source: "curated" },
  { name: "Dadar Police Station, Mumbai", address: "Dadar West, Mumbai", city: "Mumbai", state: "Maharashtra", pincode: "400028", phone: "022-24222222", lat: 19.0176, lng: 72.8476, openHours: "24x7", jurisdiction: "Mumbai Central", source: "curated" },
  { name: "Indiranagar Police Station, Bengaluru", address: "100 Feet Road, Indiranagar, Bengaluru", city: "Bengaluru", state: "Karnataka", pincode: "560038", phone: "080-25292200", lat: 12.9719, lng: 77.6412, openHours: "24x7", jurisdiction: "Bengaluru East", source: "curated" },
  { name: "Anna Nagar Police Station, Chennai", address: "Anna Nagar, Chennai", city: "Chennai", state: "Tamil Nadu", pincode: "600040", phone: "044-26213333", lat: 13.0850, lng: 80.2101, openHours: "24x7", jurisdiction: "Chennai West", source: "curated" },
  { name: "Ameerpet Police Station, Hyderabad", address: "Ameerpet, Hyderabad", city: "Hyderabad", state: "Telangana", pincode: "500016", phone: "040-23400100", lat: 17.4374, lng: 78.4487, openHours: "24x7", jurisdiction: "Hyderabad Central", source: "curated" },
  { name: "Karol Bagh Police Station, Delhi", address: "Karol Bagh, New Delhi", city: "New Delhi", state: "Delhi", pincode: "110005", phone: "011-23541100", lat: 28.6517, lng: 77.1909, openHours: "24x7", jurisdiction: "Central Delhi", source: "curated" },
  { name: "Gomti Nagar Police Station, Lucknow", address: "Gomti Nagar, Lucknow", city: "Lucknow", state: "Uttar Pradesh", pincode: "226010", phone: "0522-2300100", lat: 26.8607, lng: 80.9989, openHours: "24x7", jurisdiction: "Lucknow East", source: "curated" },
  { name: "Ballygunge Police Station, Kolkata", address: "Ballygunge, Kolkata", city: "Kolkata", state: "West Bengal", pincode: "700019", phone: "033-24603900", lat: 22.5340, lng: 88.3647, openHours: "24x7", jurisdiction: "Kolkata South", source: "curated" },
  { name: "Kothrud Police Station, Pune", address: "Kothrud, Pune", city: "Pune", state: "Maharashtra", pincode: "411038", phone: "020-25384400", lat: 18.5074, lng: 73.8077, openHours: "24x7", jurisdiction: "Pune West", source: "curated" },
  { name: "Sector 29 Police Station, Noida", address: "Sector 29, Noida", city: "Noida", state: "Uttar Pradesh", pincode: "201301", phone: "0120-2450100", lat: 28.5708, lng: 77.3260, openHours: "24x7", jurisdiction: "Noida Central", source: "curated" },
  { name: "Cyberabad Police Station, Madhapur", address: "Madhapur, Hyderabad", city: "Hyderabad", state: "Telangana", pincode: "500081", phone: "040-23405400", lat: 17.4483, lng: 78.3915, openHours: "24x7", jurisdiction: "Cyberabad IT Corridor", source: "curated" },
  { name: "Vastrapur Police Station, Ahmedabad", address: "Vastrapur, Ahmedabad", city: "Ahmedabad", state: "Gujarat", pincode: "380015", phone: "079-26760100", lat: 23.0379, lng: 72.5290, openHours: "24x7", jurisdiction: "Ahmedabad West", source: "curated" },
  { name: "Thillai Nagar Police Station, Trichy", address: "Thillai Nagar, Tiruchirappalli", city: "Tiruchirappalli", state: "Tamil Nadu", pincode: "620018", phone: "0431-2422100", lat: 10.7905, lng: 78.7047, openHours: "24x7", jurisdiction: "Trichy City", source: "curated" },
  { name: "Paltan Bazaar Police Station, Guwahati", address: "Paltan Bazaar, Guwahati", city: "Guwahati", state: "Assam", pincode: "781008", phone: "0361-2730555", lat: 26.1715, lng: 91.7657, openHours: "24x7", jurisdiction: "Guwahati Central", source: "curated" },
  { name: "Lal Bagh Police Station, Indore", address: "Lal Bagh, Indore", city: "Indore", state: "Madhya Pradesh", pincode: "452001", phone: "0731-2427100", lat: 22.7196, lng: 75.8577, openHours: "24x7", jurisdiction: "Indore City", source: "curated" },
  { name: "Budhwar Peth Police Station, Solapur", address: "Budhwar Peth, Solapur", city: "Solapur", state: "Maharashtra", pincode: "413002", phone: "0217-2300100", lat: 17.6599, lng: 75.9064, openHours: "24x7", jurisdiction: "Solapur City", source: "curated" },
  { name: "M.G. Road Police Station, Vijayawada", address: "MG Road, Vijayawada", city: "Vijayawada", state: "Andhra Pradesh", pincode: "520002", phone: "0866-2422100", lat: 16.5062, lng: 80.6480, openHours: "24x7", jurisdiction: "Vijayawada City", source: "curated" },
  { name: "Sadar Bazaar Police Station, Agra", address: "Sadar Bazaar, Agra", city: "Agra", state: "Uttar Pradesh", pincode: "282001", phone: "0562-2220100", lat: 27.1750, lng: 78.0421, openHours: "24x7", jurisdiction: "Agra City", source: "curated" },
  { name: "Connaught Place Police Station, Dehradun", address: "Connaught Place, Dehradun", city: "Dehradun", state: "Uttarakhand", pincode: "248001", phone: "0135-2652100", lat: 30.3165, lng: 78.0322, openHours: "24x7", jurisdiction: "Dehradun City", source: "curated" },
  { name: "Kacheripady Police Station, Kochi", address: "Kacheripady, Ernakulam", city: "Kochi", state: "Kerala", pincode: "682018", phone: "0484-2391800", lat: 9.9930, lng: 76.2790, openHours: "24x7", jurisdiction: "Ernakulam North", source: "curated" },
  { name: "Ranip Police Station, Ahmedabad", address: "Ranip, Ahmedabad", city: "Ahmedabad", state: "Gujarat", pincode: "382480", phone: "079-27540100", lat: 23.0831, lng: 72.5827, openHours: "24x7", jurisdiction: "Ahmedabad North", source: "curated" },
] as const;

export const TEMPLATES = [
  {
    slug: "fir-draft",
    title: "FIR Draft (First Information Report)",
    description: "A template you can adapt when filing an FIR at the police station under BNSS Section 173.",
    body: "To\nThe Station House Officer\n______________ Police Station\n______________ (City), Pin: __________\n\nSub: FIR regarding ___________________________________________________\n\nSir/Madam,\n\nI, ______________________ (name), aged _____ years, son/daughter/wife of ______________________, residing at __________________________________________________ (full address), do hereby inform you that on ______ (date) at about ______ (time) at __________________ (place), the following incident occurred:\n\n(Describe the incident factually: who, what, when, where, how. Mention names, numbers, vehicle numbers, and any property involved. Stick to facts. Do not speculate.)\n\nThe above constitutes a cognizable offence. I therefore request that an FIR be registered and investigation taken up.\n\nI state that the contents of this complaint are true to my knowledge.\n\nDate: __________\nPlace: __________\n\nSignature / Thumb impression\nName: ______________________\nContact: ______________________",
    category: "criminal",
  },
  {
    slug: "rti-application",
    title: "RTI Application",
    description: "Application under the Right to Information Act, 2005.",
    body: "To\nThe Public Information Officer\n________________________________ (office)\n________________________________ (address)\n\nSub: Application under the Right to Information Act, 2005\n\nSir/Madam,\n\nBeing a citizen of India, I hereby request the following information under Section 6(1) of the Right to Information Act, 2005:\n\n1. __________________________________________________________\n2. __________________________________________________________\n3. __________________________________________________________\n\nI request that the information be supplied in: (English / Hindi / regional language) and by: (post / email).\n\nI am attaching a fee of ₹10 (Indian Postal Order / court-fee stamp / demand draft). For BPL applicants the fee is waived.\n\nIf the information is denied, kindly provide the name and address of the First Appellate Authority under Section 19(1).\n\nDate: __________\nPlace: __________\n\nSignature\nName: ______________________\nAddress: ______________________\nContact: ______________________",
    category: "rti",
  },
  {
    slug: "consumer-complaint",
    title: "Consumer Complaint (to District Commission)",
    description: "Format under the Consumer Protection Act, 2019.",
    body: "BEFORE THE DISTRICT CONSUMER DISPUTES REDRESSAL COMMISSION AT ______________\n\nCOMPLAINT UNDER SECTION 35 OF THE CONSUMER PROTECTION ACT, 2019\n\nIN THE MATTER OF:\n\n______________________ (Complainant), aged ___, resident of ______________________\n\nVERSUS\n\n______________________ (Opposite Party), having office at ______________________\n\nBRIEF FACTS:\n\n1. The complainant purchased/availed of the following goods/services from the opposite party on ______: ____________.\n2. The complaint pertains to: (describe deficiency in service / defect in goods / unfair trade practice / misleading advertisement).\n3. The opposite party was given notice dated ______ to remedy the deficiency; the opposite party has failed/refused.\n4. The complainant has suffered loss of ₹________ and mental harassment.\n\nRELIEF SOUGHT:\n\na) Direct the opposite party to replace / repair / refund ₹________.\nb) Award compensation of ₹________ for deficiency, harassment, and litigation costs.\nc) Pass any other order the Commission deems fit.\n\nDate: __________\nPlace: __________\n\nThrough Counsel / Self\nSignature of Complainant",
    category: "consumer",
  },
  {
    slug: "legal-notice",
    title: "Legal Notice (civil)",
    description: "A formal legal notice before initiating a civil suit. Send by registered post + email.",
    body: "NOTICE\n\nFrom:\n______________________ (name), resident of ______________________\n\nTo:\n______________________ (name / company), having office at ______________________\n\nDate: __________\n\nSir/Madam,\n\nUnder instructions from my client, I hereby give you notice as follows:\n\n1. My client is aggrieved by your act of ____________________ (describe the breach, default, injury, or wrong).\n2. The said act is contrary to the agreement / statute / general law in that ____________________.\n3. In the circumstances, my client is entitled to ____________________.\n\nI hereby call upon you to comply with the following within 15 (fifteen) days of receipt of this notice, failing which my client shall be constrained to initiate appropriate civil and/or criminal proceedings against you at your risk as to costs and consequences.\n\nA copy of this notice is retained in my office for record.\n\nDate: __________\nAdvocate / Self",
    category: "civil",
  },
  {
    slug: "affidavit",
    title: "General Affidavit",
    description: "A standard affidavit format to be sworn before a Notary / Oath Commissioner.",
    body: "AFFIDAVIT\n\nI, ______________________ (name), aged _____ years, son/daughter/wife of ______________________, residing at __________________________________________________, do hereby solemnly affirm and declare as follows:\n\n1. __________________________________________________________\n2. __________________________________________________________\n3. __________________________________________________________\n\nI declare that the statements made above are true and correct to the best of my knowledge and belief.\n\nDEPONENT\n\nVerified at __________ on this the _____ day of __________, 20___.\n\nDEPONENT",
    category: "general",
  },
] as const;

export const GLOSSARY = [
  { term: "FIR", meaning: "First Information Report. The first written record of a cognizable offence, registered by police under Section 173 of the BNSS, 2023 (earlier Section 154 CrPC)." },
  { term: "Cognizable offence", meaning: "An offence for which police can arrest without a warrant and start investigation without court permission. Usually serious crimes (murder, rape, theft)." },
  { term: "Non-cognizable offence", meaning: "An offence for which police cannot arrest without a warrant and cannot investigate without a magistrate's permission." },
  { term: "Bailable offence", meaning: "An offence where bail is a right — the police or court must grant bail." },
  { term: "Non-bailable offence", meaning: "An offence where bail is at the discretion of the court. Does NOT mean bail cannot be granted." },
  { term: "Bail", meaning: "The temporary release of an accused person pending trial, on furnishing a bond with or without sureties." },
  { term: "Anticipatory bail", meaning: "Bail granted by the High Court or Sessions Court in anticipation of arrest — under Section 482 BNSS (earlier Section 438 CrPC)." },
  { term: "BNSS", meaning: "Bharatiya Nagarik Suraksha Sanhita, 2023 — the new procedural criminal code that replaced the CrPC, effective 1 July 2024." },
  { term: "BNS", meaning: "Bharatiya Nyaya Sanhita, 2023 — the new substantive penal code that replaced the IPC, effective 1 July 2024." },
  { term: "BSA", meaning: "Bharatiya Sakshya Adhiniyam, 2023 — the new evidence law that replaced the Indian Evidence Act, effective 1 July 2024." },
  { term: "NALSA", meaning: "National Legal Services Authority — provides free legal aid to eligible persons. Helpline 15100." },
  { term: "DLSA", meaning: "District Legal Services Authority — the district-level body providing free legal aid and lok adalats." },
  { term: "POCSO", meaning: "Protection of Children from Sexual Offences Act, 2012 — special law for sexual offences against children." },
  { term: "PWDVA", meaning: "Protection of Women from Domestic Violence Act, 2005 — civil law giving women protection orders, residence rights, and maintenance." },
  { term: "RTI", meaning: "Right to Information — the Right to Information Act, 2005 lets citizens obtain information from public authorities for ₹10." },
  { term: "Lok Adalat", meaning: "'People's court' — a forum for fast, free, amicable settlement of disputes. Awards are final and binding." },
  { term: "Writ petition", meaning: "A petition to a High Court (Article 226) or the Supreme Court (Article 32) for enforcement of fundamental or legal rights." },
  { term: "Habeas corpus", meaning: "A writ ('you may have the body') requiring the authorities to produce a detained person before the court to test the legality of detention." },
  { term: "Mandamus", meaning: "A writ directing a public authority to perform its lawful public duty." },
  { term: "Limitation period", meaning: "The maximum time within which a suit or complaint must be filed. Governed by the Limitation Act, 1963." },
  { term: "MACT", meaning: "Motor Accidents Claims Tribunal — the special court that decides compensation claims for road accidents." },
  { term: "RERA", meaning: "Real Estate (Regulation and Development) Act, 2016 — protects homebuyers; grievances against builders go to RERA." },
  { term: "DPDP Act", meaning: "Digital Personal Data Protection Act, 2023 — India's data protection law for personal data." },
] as const;
